/**
 * @type {import('./types').ESLintConfig}
 */
module.exports = {
  plugins: ['jest', 'jest-formatting'],
  env: {
    'jest/globals': true,
  },
  rules: {
    // https://github.com/jest-community/eslint-plugin-jest/tree/master/docs/rules
    'jest/consistent-test-it': 'off',
    'jest/expect-expect': 'off',
    'jest/max-nested-describe': 'error',
    'jest/no-alias-methods': 'off',
    'jest/no-commented-out-tests': 'warn',
    'jest/no-conditional-expect': 'error',
    'jest/no-conditional-in-test': 'off',
    'jest/no-deprecated-functions': 'off',
    'jest/no-disabled-tests': 'warn',
    'jest/no-done-callback': 'error',
    'jest/no-duplicate-hooks': 'off',
    'jest/no-export': 'error',
    'jest/no-focused-tests': 'error',
    'jest/no-hooks': 'off',
    'jest/no-identical-title': 'error',
    'jest/no-if': 'off',
    'jest/no-interpolation-in-snapshots': 'error',
    'jest/no-jasmine-globals': 'warn',
    'jest/no-jest-import': 'error',
    'jest/no-large-snapshots': 'off',
    'jest/no-mocks-import': 'error',
    'jest/no-restricted-matchers': 'off',
    'jest/no-standalone-expect': 'error',
    'jest/no-test-prefixes': 'error',
    'jest/no-test-return-statement': 'off',
    'jest/prefer-called-with': 'off',
    'jest/prefer-comparison-matcher': 'warn',
    'jest/prefer-equality-matcher': 'warn',
    'jest/prefer-expect-assertions': 'off',
    'jest/prefer-expect-resolves': 'warn',
    'jest/prefer-hooks-on-top': 'off',
    'jest/prefer-lowercase-title': 'off',
    'jest/prefer-snapshot-hint': 'warn',
    'jest/prefer-spy-on': 'off',
    'jest/prefer-strict-equal': 'off',
    'jest/prefer-to-be': 'warn',
    'jest/prefer-to-contain': 'off',
    'jest/prefer-to-have-length': 'off',
    'jest/prefer-todo': 'off',
    'jest/require-hook': 'off',
    'jest/require-to-throw-message': 'off',
    'jest/require-top-level-describe': 'off',
    'jest/unbound-method': 'off',
    'jest/valid-describe-callback': 'error',
    'jest/valid-expect-in-promise': 'error',
    'jest/valid-expect': 'error',
    'jest/valid-title': 'off',

    // https://github.com/dangreenisrael/eslint-plugin-jest-formatting/tree/master/docs/rules
    'jest-formatting/padding-around-after-all-blocks': 'warn',
    'jest-formatting/padding-around-after-each-blocks': 'warn',
    'jest-formatting/padding-around-all': 'off',
    'jest-formatting/padding-around-before-all-blocks': 'warn',
    'jest-formatting/padding-around-before-each-blocks': 'warn',
    'jest-formatting/padding-around-describe-blocks': 'warn',
    'jest-formatting/padding-around-expect-groups': 'off',
    'jest-formatting/padding-around-test-blocks': 'warn',
  },
}
