// generated by _generateIntegrationLists.ts. Do not modify by hand
import {default as integrationAirtable_def} from '@usevenice/connector-airtable/def'
import {default as integrationAirtable_server} from '@usevenice/connector-airtable/server'
import {default as integrationBeancount_def} from '@usevenice/connector-beancount/def'
import {default as integrationBeancount_server} from '@usevenice/connector-beancount/server'
import {default as integrationBrex_def} from '@usevenice/connector-brex/def'
import {default as integrationBrex_server} from '@usevenice/connector-brex/server'
import {default as integrationDebug_def} from '@usevenice/connector-debug/def'
import {default as integrationDebug_server} from '@usevenice/connector-debug/server'
import {default as integrationDiscord_def} from '@usevenice/connector-discord/def'
import {default as integrationDiscord_server} from '@usevenice/connector-discord/server'
import {default as integrationFirebase_def} from '@usevenice/connector-firebase/def'
import {default as integrationFirebase_server} from '@usevenice/connector-firebase/server'
import {default as integrationForeceipt_def} from '@usevenice/connector-foreceipt/def'
import {default as integrationForeceipt_server} from '@usevenice/connector-foreceipt/server'
import {default as integrationFs_def} from '@usevenice/connector-fs/def'
import {default as integrationFs_server} from '@usevenice/connector-fs/server'
import {default as integrationHeron_def} from '@usevenice/connector-heron/def'
import {default as integrationHeron_server} from '@usevenice/connector-heron/server'
import {default as integrationLunchmoney_def} from '@usevenice/connector-lunchmoney/def'
import {default as integrationLunchmoney_server} from '@usevenice/connector-lunchmoney/server'
import {default as integrationMercury_def} from '@usevenice/connector-mercury/def'
import {default as integrationMerge_def} from '@usevenice/connector-merge/def'
import {default as integrationMerge_server} from '@usevenice/connector-merge/server'
import {default as integrationMongodb_def} from '@usevenice/connector-mongodb/def'
import {default as integrationMongodb_server} from '@usevenice/connector-mongodb/server'
import {default as integrationMoota_def} from '@usevenice/connector-moota/def'
import {default as integrationMoota_server} from '@usevenice/connector-moota/server'
import {default as integrationOnebrick_def} from '@usevenice/connector-onebrick/def'
import {default as integrationOnebrick_server} from '@usevenice/connector-onebrick/server'
import {default as integrationPlaid_def} from '@usevenice/connector-plaid/def'
import {default as integrationPlaid_server} from '@usevenice/connector-plaid/server'
import {default as integrationPostgres_def} from '@usevenice/connector-postgres/def'
import {default as integrationPostgres_server} from '@usevenice/connector-postgres/server'
import {default as integrationQbo_def} from '@usevenice/connector-qbo/def'
import {default as integrationQbo_server} from '@usevenice/connector-qbo/server'
import {default as integrationRamp_def} from '@usevenice/connector-ramp/def'
import {default as integrationRamp_server} from '@usevenice/connector-ramp/server'
import {default as integrationSaltedge_def} from '@usevenice/connector-saltedge/def'
import {default as integrationSaltedge_server} from '@usevenice/connector-saltedge/server'
import {default as integrationSplitwise_def} from '@usevenice/connector-splitwise/def'
import {default as integrationSplitwise_server} from '@usevenice/connector-splitwise/server'
import {default as integrationSpreadsheet_def} from '@usevenice/connector-spreadsheet/def'
import {default as integrationSpreadsheet_server} from '@usevenice/connector-spreadsheet/server'
import {default as integrationStripe_def} from '@usevenice/connector-stripe/def'
import {default as integrationStripe_server} from '@usevenice/connector-stripe/server'
import {default as integrationTeller_def} from '@usevenice/connector-teller/def'
import {default as integrationTeller_server} from '@usevenice/connector-teller/server'
import {default as integrationToggl_def} from '@usevenice/connector-toggl/def'
import {default as integrationToggl_server} from '@usevenice/connector-toggl/server'
import {default as integrationVenmo_def} from '@usevenice/connector-venmo/def'
import {default as integrationWebhook_def} from '@usevenice/connector-webhook/def'
import {default as integrationWebhook_server} from '@usevenice/connector-webhook/server'
import {default as integrationWise_def} from '@usevenice/connector-wise/def'
import {default as integrationWise_server} from '@usevenice/connector-wise/server'
import {default as integrationYodlee_def} from '@usevenice/connector-yodlee/def'
import {default as integrationYodlee_server} from '@usevenice/connector-yodlee/server'

const integrationAirtable = {
  ...integrationAirtable_def,
  ...integrationAirtable_server,
}

const integrationBeancount = {
  ...integrationBeancount_def,
  ...integrationBeancount_server,
}

const integrationBrex = {
  ...integrationBrex_def,
  ...integrationBrex_server,
}

const integrationDebug = {
  ...integrationDebug_def,
  ...integrationDebug_server,
}

const integrationDiscord = {
  ...integrationDiscord_def,
  ...integrationDiscord_server,
}

const integrationFirebase = {
  ...integrationFirebase_def,
  ...integrationFirebase_server,
}

const integrationForeceipt = {
  ...integrationForeceipt_def,
  ...integrationForeceipt_server,
}

const integrationFs = {
  ...integrationFs_def,
  ...integrationFs_server,
}

const integrationHeron = {
  ...integrationHeron_def,
  ...integrationHeron_server,
}

const integrationLunchmoney = {
  ...integrationLunchmoney_def,
  ...integrationLunchmoney_server,
}

const integrationMercury = {
  ...integrationMercury_def,
}

const integrationMerge = {
  ...integrationMerge_def,
  ...integrationMerge_server,
}

const integrationMongodb = {
  ...integrationMongodb_def,
  ...integrationMongodb_server,
}

const integrationMoota = {
  ...integrationMoota_def,
  ...integrationMoota_server,
}

const integrationOnebrick = {
  ...integrationOnebrick_def,
  ...integrationOnebrick_server,
}

const integrationPlaid = {
  ...integrationPlaid_def,
  ...integrationPlaid_server,
}

const integrationPostgres = {
  ...integrationPostgres_def,
  ...integrationPostgres_server,
}

const integrationQbo = {
  ...integrationQbo_def,
  ...integrationQbo_server,
}

const integrationRamp = {
  ...integrationRamp_def,
  ...integrationRamp_server,
}

const integrationSaltedge = {
  ...integrationSaltedge_def,
  ...integrationSaltedge_server,
}

const integrationSplitwise = {
  ...integrationSplitwise_def,
  ...integrationSplitwise_server,
}

const integrationSpreadsheet = {
  ...integrationSpreadsheet_def,
  ...integrationSpreadsheet_server,
}

const integrationStripe = {
  ...integrationStripe_def,
  ...integrationStripe_server,
}

const integrationTeller = {
  ...integrationTeller_def,
  ...integrationTeller_server,
}

const integrationToggl = {
  ...integrationToggl_def,
  ...integrationToggl_server,
}

const integrationVenmo = {
  ...integrationVenmo_def,
}

const integrationWebhook = {
  ...integrationWebhook_def,
  ...integrationWebhook_server,
}

const integrationWise = {
  ...integrationWise_def,
  ...integrationWise_server,
}

const integrationYodlee = {
  ...integrationYodlee_def,
  ...integrationYodlee_server,
}

export const mergedIntegrations = {
  airtable: integrationAirtable,
  beancount: integrationBeancount,
  brex: integrationBrex,
  debug: integrationDebug,
  discord: integrationDiscord,
  firebase: integrationFirebase,
  foreceipt: integrationForeceipt,
  fs: integrationFs,
  heron: integrationHeron,
  lunchmoney: integrationLunchmoney,
  mercury: integrationMercury,
  merge: integrationMerge,
  mongodb: integrationMongodb,
  moota: integrationMoota,
  onebrick: integrationOnebrick,
  plaid: integrationPlaid,
  postgres: integrationPostgres,
  qbo: integrationQbo,
  ramp: integrationRamp,
  saltedge: integrationSaltedge,
  splitwise: integrationSplitwise,
  spreadsheet: integrationSpreadsheet,
  stripe: integrationStripe,
  teller: integrationTeller,
  toggl: integrationToggl,
  venmo: integrationVenmo,
  webhook: integrationWebhook,
  wise: integrationWise,
  yodlee: integrationYodlee,
}
