// generated by _generateIntegrationLists.ts. Do not modify by hand
import {default as integrationBrex_def} from '@usevenice/integration-brex/def'
import {default as integrationBrex_server} from '@usevenice/integration-brex/server'
import {default as integrationHeron_def} from '@usevenice/integration-heron/def'
import {default as integrationHeron_server} from '@usevenice/integration-heron/server'
import {default as integrationMercury_def} from '@usevenice/integration-mercury/def'
import {default as integrationMerge_client} from '@usevenice/integration-merge/client'
import {default as integrationMerge_def} from '@usevenice/integration-merge/def'
import {default as integrationMerge_server} from '@usevenice/integration-merge/server'
import {default as integrationOnebrick_client} from '@usevenice/integration-onebrick/client'
import {default as integrationOnebrick_def} from '@usevenice/integration-onebrick/def'
import {default as integrationOnebrick_server} from '@usevenice/integration-onebrick/server'
import {default as integrationPlaid_client} from '@usevenice/integration-plaid/client'
import {default as integrationPlaid_def} from '@usevenice/integration-plaid/def'
import {default as integrationPlaid_server} from '@usevenice/integration-plaid/server'
import {default as integrationStripe_def} from '@usevenice/integration-stripe/def'
import {default as integrationStripe_server} from '@usevenice/integration-stripe/server'
import {default as integrationTeller_client} from '@usevenice/integration-teller/client'
import {default as integrationTeller_def} from '@usevenice/integration-teller/def'
import {default as integrationTeller_server} from '@usevenice/integration-teller/server'
import {default as integrationYodlee_client} from '@usevenice/integration-yodlee/client'
import {default as integrationYodlee_def} from '@usevenice/integration-yodlee/def'
import {default as integrationYodlee_server} from '@usevenice/integration-yodlee/server'

const integrationBrex = {
  ...integrationBrex_def,
  ...integrationBrex_server,
}

const integrationHeron = {
  ...integrationHeron_def,
  ...integrationHeron_server,
}

const integrationMercury = {
  ...integrationMercury_def,
}

const integrationMerge = {
  ...integrationMerge_def,
  ...integrationMerge_client,
  ...integrationMerge_server,
}

const integrationOnebrick = {
  ...integrationOnebrick_def,
  ...integrationOnebrick_client,
  ...integrationOnebrick_server,
}

const integrationPlaid = {
  ...integrationPlaid_def,
  ...integrationPlaid_client,
  ...integrationPlaid_server,
}

const integrationStripe = {
  ...integrationStripe_def,
  ...integrationStripe_server,
}

const integrationTeller = {
  ...integrationTeller_def,
  ...integrationTeller_client,
  ...integrationTeller_server,
}

const integrationYodlee = {
  ...integrationYodlee_def,
  ...integrationYodlee_client,
  ...integrationYodlee_server,
}

export const mergedIntegrations = {
  brex: integrationBrex,
  heron: integrationHeron,
  mercury: integrationMercury,
  merge: integrationMerge,
  onebrick: integrationOnebrick,
  plaid: integrationPlaid,
  stripe: integrationStripe,
  teller: integrationTeller,
  yodlee: integrationYodlee,
}
