// generated by _generateIntegrationLists.ts. Do not modify by hand
import {default as integrationAirtable} from '@usevenice/integration-airtable/server'
import {default as integrationBrex} from '@usevenice/integration-brex/server'
import {default as integrationForeceipt} from '@usevenice/integration-foreceipt/server'
import {default as integrationHeron} from '@usevenice/integration-heron/server'
import {default as integrationMerge} from '@usevenice/integration-merge/server'
import {default as integrationMoota} from '@usevenice/integration-moota/server'
import {default as integrationOnebrick} from '@usevenice/integration-onebrick/server'
import {default as integrationPlaid} from '@usevenice/integration-plaid/server'
import {default as integrationQbo} from '@usevenice/integration-qbo/server'
import {default as integrationSaltedge} from '@usevenice/integration-saltedge/server'
import {default as integrationSplitwise} from '@usevenice/integration-splitwise/server'
import {default as integrationStripe} from '@usevenice/integration-stripe/server'
import {default as integrationTeller} from '@usevenice/integration-teller/server'
import {default as integrationToggl} from '@usevenice/integration-toggl/server'
import {default as integrationYodlee} from '@usevenice/integration-yodlee/server'

export const serverIntegrations = {
  airtable: integrationAirtable,
  brex: integrationBrex,
  foreceipt: integrationForeceipt,
  heron: integrationHeron,
  merge: integrationMerge,
  moota: integrationMoota,
  onebrick: integrationOnebrick,
  plaid: integrationPlaid,
  qbo: integrationQbo,
  saltedge: integrationSaltedge,
  splitwise: integrationSplitwise,
  stripe: integrationStripe,
  teller: integrationTeller,
  toggl: integrationToggl,
  yodlee: integrationYodlee,
}
