// generated by _generateConnectorLists.ts. Do not modify by hand
import {default as integrationMerge} from '@usevenice/connector-merge/client'
import {default as integrationOnebrick} from '@usevenice/connector-onebrick/client'
import {default as integrationPlaid} from '@usevenice/connector-plaid/client'
import {default as integrationTeller} from '@usevenice/connector-teller/client'
import {default as integrationYodlee} from '@usevenice/connector-yodlee/client'

export const clientIntegrations = {
  merge: integrationMerge,
  onebrick: integrationOnebrick,
  plaid: integrationPlaid,
  teller: integrationTeller,
  yodlee: integrationYodlee,
}
