// generated by _generateIntegrationLists.ts. Do not modify by hand
import {default as integrationAirtable} from '@usevenice/integration-airtable/def'
import {default as integrationBrex} from '@usevenice/integration-brex/def'
import {default as integrationHeron} from '@usevenice/integration-heron/def'
import {default as integrationMercury} from '@usevenice/integration-mercury/def'
import {default as integrationMerge} from '@usevenice/integration-merge/def'
import {default as integrationMoota} from '@usevenice/integration-moota/def'
import {default as integrationOnebrick} from '@usevenice/integration-onebrick/def'
import {default as integrationPlaid} from '@usevenice/integration-plaid/def'
import {default as integrationQbo} from '@usevenice/integration-qbo/def'
import {default as integrationSaltedge} from '@usevenice/integration-saltedge/def'
import {default as integrationStripe} from '@usevenice/integration-stripe/def'
import {default as integrationTeller} from '@usevenice/integration-teller/def'
import {default as integrationVenmo} from '@usevenice/integration-venmo/def'
import {default as integrationYodlee} from '@usevenice/integration-yodlee/def'

export const defIntegrations = {
  airtable: integrationAirtable,
  brex: integrationBrex,
  heron: integrationHeron,
  mercury: integrationMercury,
  merge: integrationMerge,
  moota: integrationMoota,
  onebrick: integrationOnebrick,
  plaid: integrationPlaid,
  qbo: integrationQbo,
  saltedge: integrationSaltedge,
  stripe: integrationStripe,
  teller: integrationTeller,
  venmo: integrationVenmo,
  yodlee: integrationYodlee,
}
