// generated by _generateIntegrationLists.ts. Do not modify by hand
import {default as integrationBrex} from '@usevenice/integration-brex/server'
import {default as integrationHeron} from '@usevenice/integration-heron/server'
import {default as integrationMerge} from '@usevenice/integration-merge/server'
import {default as integrationOnebrick} from '@usevenice/integration-onebrick/server'
import {default as integrationPlaid} from '@usevenice/integration-plaid/server'
import {default as integrationStripe} from '@usevenice/integration-stripe/server'
import {default as integrationTeller} from '@usevenice/integration-teller/server'
import {default as integrationYodlee} from '@usevenice/integration-yodlee/server'

export const serverIntegrations = {
  brex: integrationBrex,
  heron: integrationHeron,
  merge: integrationMerge,
  onebrick: integrationOnebrick,
  plaid: integrationPlaid,
  stripe: integrationStripe,
  teller: integrationTeller,
  yodlee: integrationYodlee,
}
