// generated by _generateIntegrationLists.ts. Do not modify by hand
import {default as integrationAirtable} from '@usevenice/connector-airtable/server'
import {default as integrationBeancount} from '@usevenice/connector-beancount/server'
import {default as integrationBrex} from '@usevenice/connector-brex/server'
import {default as integrationDebug} from '@usevenice/connector-debug/server'
import {default as integrationDiscord} from '@usevenice/connector-discord/server'
import {default as integrationFirebase} from '@usevenice/connector-firebase/server'
import {default as integrationForeceipt} from '@usevenice/connector-foreceipt/server'
import {default as integrationFs} from '@usevenice/connector-fs/server'
import {default as integrationHeron} from '@usevenice/connector-heron/server'
import {default as integrationLunchmoney} from '@usevenice/connector-lunchmoney/server'
import {default as integrationMerge} from '@usevenice/connector-merge/server'
import {default as integrationMongodb} from '@usevenice/connector-mongodb/server'
import {default as integrationMoota} from '@usevenice/connector-moota/server'
import {default as integrationOnebrick} from '@usevenice/connector-onebrick/server'
import {default as integrationPlaid} from '@usevenice/connector-plaid/server'
import {default as integrationPostgres} from '@usevenice/connector-postgres/server'
import {default as integrationQbo} from '@usevenice/connector-qbo/server'
import {default as integrationRamp} from '@usevenice/connector-ramp/server'
import {default as integrationSaltedge} from '@usevenice/connector-saltedge/server'
import {default as integrationSplitwise} from '@usevenice/connector-splitwise/server'
import {default as integrationSpreadsheet} from '@usevenice/connector-spreadsheet/server'
import {default as integrationStripe} from '@usevenice/connector-stripe/server'
import {default as integrationTeller} from '@usevenice/connector-teller/server'
import {default as integrationToggl} from '@usevenice/connector-toggl/server'
import {default as integrationWebhook} from '@usevenice/connector-webhook/server'
import {default as integrationWise} from '@usevenice/connector-wise/server'
import {default as integrationYodlee} from '@usevenice/connector-yodlee/server'

export const serverIntegrations = {
  airtable: integrationAirtable,
  beancount: integrationBeancount,
  brex: integrationBrex,
  debug: integrationDebug,
  discord: integrationDiscord,
  firebase: integrationFirebase,
  foreceipt: integrationForeceipt,
  fs: integrationFs,
  heron: integrationHeron,
  lunchmoney: integrationLunchmoney,
  merge: integrationMerge,
  mongodb: integrationMongodb,
  moota: integrationMoota,
  onebrick: integrationOnebrick,
  plaid: integrationPlaid,
  postgres: integrationPostgres,
  qbo: integrationQbo,
  ramp: integrationRamp,
  saltedge: integrationSaltedge,
  splitwise: integrationSplitwise,
  spreadsheet: integrationSpreadsheet,
  stripe: integrationStripe,
  teller: integrationTeller,
  toggl: integrationToggl,
  webhook: integrationWebhook,
  wise: integrationWise,
  yodlee: integrationYodlee,
}
