// generated by _generateIntegrationLists.ts. Do not modify by hand
import {default as integrationAirtable_def} from '@usevenice/integration-airtable/def'
import {default as integrationAirtable_server} from '@usevenice/integration-airtable/server'
import {default as integrationBeancount_def} from '@usevenice/integration-beancount/def'
import {default as integrationBeancount_server} from '@usevenice/integration-beancount/server'
import {default as integrationBrex_def} from '@usevenice/integration-brex/def'
import {default as integrationBrex_server} from '@usevenice/integration-brex/server'
import {default as integrationFirebase_def} from '@usevenice/integration-firebase/def'
import {default as integrationFirebase_server} from '@usevenice/integration-firebase/server'
import {default as integrationForeceipt_def} from '@usevenice/integration-foreceipt/def'
import {default as integrationForeceipt_server} from '@usevenice/integration-foreceipt/server'
import {default as integrationFs_def} from '@usevenice/integration-fs/def'
import {default as integrationFs_server} from '@usevenice/integration-fs/server'
import {default as integrationHeron_def} from '@usevenice/integration-heron/def'
import {default as integrationHeron_server} from '@usevenice/integration-heron/server'
import {default as integrationLunchmoney_def} from '@usevenice/integration-lunchmoney/def'
import {default as integrationLunchmoney_server} from '@usevenice/integration-lunchmoney/server'
import {default as integrationMercury_def} from '@usevenice/integration-mercury/def'
import {default as integrationMerge_client} from '@usevenice/integration-merge/client'
import {default as integrationMerge_def} from '@usevenice/integration-merge/def'
import {default as integrationMerge_server} from '@usevenice/integration-merge/server'
import {default as integrationMoota_def} from '@usevenice/integration-moota/def'
import {default as integrationMoota_server} from '@usevenice/integration-moota/server'
import {default as integrationOnebrick_client} from '@usevenice/integration-onebrick/client'
import {default as integrationOnebrick_def} from '@usevenice/integration-onebrick/def'
import {default as integrationOnebrick_server} from '@usevenice/integration-onebrick/server'
import {default as integrationPlaid_client} from '@usevenice/integration-plaid/client'
import {default as integrationPlaid_def} from '@usevenice/integration-plaid/def'
import {default as integrationPlaid_server} from '@usevenice/integration-plaid/server'
import {default as integrationPostgres_def} from '@usevenice/integration-postgres/def'
import {default as integrationPostgres_server} from '@usevenice/integration-postgres/server'
import {default as integrationQbo_def} from '@usevenice/integration-qbo/def'
import {default as integrationQbo_server} from '@usevenice/integration-qbo/server'
import {default as integrationRamp_def} from '@usevenice/integration-ramp/def'
import {default as integrationRamp_server} from '@usevenice/integration-ramp/server'
import {default as integrationSaltedge_def} from '@usevenice/integration-saltedge/def'
import {default as integrationSaltedge_server} from '@usevenice/integration-saltedge/server'
import {default as integrationSplitwise_def} from '@usevenice/integration-splitwise/def'
import {default as integrationSplitwise_server} from '@usevenice/integration-splitwise/server'
import {default as integrationSpreadsheet_def} from '@usevenice/integration-spreadsheet/def'
import {default as integrationSpreadsheet_server} from '@usevenice/integration-spreadsheet/server'
import {default as integrationStripe_def} from '@usevenice/integration-stripe/def'
import {default as integrationStripe_server} from '@usevenice/integration-stripe/server'
import {default as integrationTeller_client} from '@usevenice/integration-teller/client'
import {default as integrationTeller_def} from '@usevenice/integration-teller/def'
import {default as integrationTeller_server} from '@usevenice/integration-teller/server'
import {default as integrationToggl_def} from '@usevenice/integration-toggl/def'
import {default as integrationToggl_server} from '@usevenice/integration-toggl/server'
import {default as integrationVenmo_def} from '@usevenice/integration-venmo/def'
import {default as integrationWise_def} from '@usevenice/integration-wise/def'
import {default as integrationWise_server} from '@usevenice/integration-wise/server'
import {default as integrationYodlee_client} from '@usevenice/integration-yodlee/client'
import {default as integrationYodlee_def} from '@usevenice/integration-yodlee/def'
import {default as integrationYodlee_server} from '@usevenice/integration-yodlee/server'

const integrationAirtable = {
  ...integrationAirtable_def,
  ...integrationAirtable_server,
}

const integrationBeancount = {
  ...integrationBeancount_def,
  ...integrationBeancount_server,
}

const integrationBrex = {
  ...integrationBrex_def,
  ...integrationBrex_server,
}

const integrationFirebase = {
  ...integrationFirebase_def,
  ...integrationFirebase_server,
}

const integrationForeceipt = {
  ...integrationForeceipt_def,
  ...integrationForeceipt_server,
}

const integrationFs = {
  ...integrationFs_def,
  ...integrationFs_server,
}

const integrationHeron = {
  ...integrationHeron_def,
  ...integrationHeron_server,
}

const integrationLunchmoney = {
  ...integrationLunchmoney_def,
  ...integrationLunchmoney_server,
}

const integrationMercury = {
  ...integrationMercury_def,
}

const integrationMerge = {
  ...integrationMerge_def,
  ...integrationMerge_client,
  ...integrationMerge_server,
}

const integrationMoota = {
  ...integrationMoota_def,
  ...integrationMoota_server,
}

const integrationOnebrick = {
  ...integrationOnebrick_def,
  ...integrationOnebrick_client,
  ...integrationOnebrick_server,
}

const integrationPlaid = {
  ...integrationPlaid_def,
  ...integrationPlaid_client,
  ...integrationPlaid_server,
}

const integrationPostgres = {
  ...integrationPostgres_def,
  ...integrationPostgres_server,
}

const integrationQbo = {
  ...integrationQbo_def,
  ...integrationQbo_server,
}

const integrationRamp = {
  ...integrationRamp_def,
  ...integrationRamp_server,
}

const integrationSaltedge = {
  ...integrationSaltedge_def,
  ...integrationSaltedge_server,
}

const integrationSplitwise = {
  ...integrationSplitwise_def,
  ...integrationSplitwise_server,
}

const integrationSpreadsheet = {
  ...integrationSpreadsheet_def,
  ...integrationSpreadsheet_server,
}

const integrationStripe = {
  ...integrationStripe_def,
  ...integrationStripe_server,
}

const integrationTeller = {
  ...integrationTeller_def,
  ...integrationTeller_client,
  ...integrationTeller_server,
}

const integrationToggl = {
  ...integrationToggl_def,
  ...integrationToggl_server,
}

const integrationVenmo = {
  ...integrationVenmo_def,
}

const integrationWise = {
  ...integrationWise_def,
  ...integrationWise_server,
}

const integrationYodlee = {
  ...integrationYodlee_def,
  ...integrationYodlee_client,
  ...integrationYodlee_server,
}

export const mergedIntegrations = {
  airtable: integrationAirtable,
  beancount: integrationBeancount,
  brex: integrationBrex,
  firebase: integrationFirebase,
  foreceipt: integrationForeceipt,
  fs: integrationFs,
  heron: integrationHeron,
  lunchmoney: integrationLunchmoney,
  mercury: integrationMercury,
  merge: integrationMerge,
  moota: integrationMoota,
  onebrick: integrationOnebrick,
  plaid: integrationPlaid,
  postgres: integrationPostgres,
  qbo: integrationQbo,
  ramp: integrationRamp,
  saltedge: integrationSaltedge,
  splitwise: integrationSplitwise,
  spreadsheet: integrationSpreadsheet,
  stripe: integrationStripe,
  teller: integrationTeller,
  toggl: integrationToggl,
  venmo: integrationVenmo,
  wise: integrationWise,
  yodlee: integrationYodlee,
}
