// generated by _generateIntegrationLists.ts. Do not modify by hand
import {default as integrationMerge} from '@usevenice/integration-merge/client'
import {default as integrationOnebrick} from '@usevenice/integration-onebrick/client'
import {default as integrationPlaid} from '@usevenice/integration-plaid/client'
import {default as integrationTeller} from '@usevenice/integration-teller/client'
import {default as integrationYodlee} from '@usevenice/integration-yodlee/client'

export const clientIntegrations = {
  merge: integrationMerge,
  onebrick: integrationOnebrick,
  plaid: integrationPlaid,
  teller: integrationTeller,
  yodlee: integrationYodlee,
}
