// generated by _generateConnectorLists.ts. Do not modify by hand
import {default as integrationAirtable} from '@usevenice/connector-airtable/def'
import {default as integrationBeancount} from '@usevenice/connector-beancount/def'
import {default as integrationBrex} from '@usevenice/connector-brex/def'
import {default as integrationDebug} from '@usevenice/connector-debug/def'
import {default as integrationDiscord} from '@usevenice/connector-discord/def'
import {default as integrationFirebase} from '@usevenice/connector-firebase/def'
import {default as integrationForeceipt} from '@usevenice/connector-foreceipt/def'
import {default as integrationFs} from '@usevenice/connector-fs/def'
import {default as integrationHeron} from '@usevenice/connector-heron/def'
import {default as integrationLunchmoney} from '@usevenice/connector-lunchmoney/def'
import {default as integrationMercury} from '@usevenice/connector-mercury/def'
import {default as integrationMerge} from '@usevenice/connector-merge/def'
import {default as integrationMongodb} from '@usevenice/connector-mongodb/def'
import {default as integrationMoota} from '@usevenice/connector-moota/def'
import {default as integrationOnebrick} from '@usevenice/connector-onebrick/def'
import {default as integrationPlaid} from '@usevenice/connector-plaid/def'
import {default as integrationPostgres} from '@usevenice/connector-postgres/def'
import {default as integrationQbo} from '@usevenice/connector-qbo/def'
import {default as integrationRamp} from '@usevenice/connector-ramp/def'
import {default as integrationSaltedge} from '@usevenice/connector-saltedge/def'
import {default as integrationSplitwise} from '@usevenice/connector-splitwise/def'
import {default as integrationSpreadsheet} from '@usevenice/connector-spreadsheet/def'
import {default as integrationStripe} from '@usevenice/connector-stripe/def'
import {default as integrationTeller} from '@usevenice/connector-teller/def'
import {default as integrationToggl} from '@usevenice/connector-toggl/def'
import {default as integrationVenmo} from '@usevenice/connector-venmo/def'
import {default as integrationWebhook} from '@usevenice/connector-webhook/def'
import {default as integrationWise} from '@usevenice/connector-wise/def'
import {default as integrationYodlee} from '@usevenice/connector-yodlee/def'

export const defIntegrations = {
  airtable: integrationAirtable,
  beancount: integrationBeancount,
  brex: integrationBrex,
  debug: integrationDebug,
  discord: integrationDiscord,
  firebase: integrationFirebase,
  foreceipt: integrationForeceipt,
  fs: integrationFs,
  heron: integrationHeron,
  lunchmoney: integrationLunchmoney,
  mercury: integrationMercury,
  merge: integrationMerge,
  mongodb: integrationMongodb,
  moota: integrationMoota,
  onebrick: integrationOnebrick,
  plaid: integrationPlaid,
  postgres: integrationPostgres,
  qbo: integrationQbo,
  ramp: integrationRamp,
  saltedge: integrationSaltedge,
  splitwise: integrationSplitwise,
  spreadsheet: integrationSpreadsheet,
  stripe: integrationStripe,
  teller: integrationTeller,
  toggl: integrationToggl,
  venmo: integrationVenmo,
  webhook: integrationWebhook,
  wise: integrationWise,
  yodlee: integrationYodlee,
}
