// generated by _generateIntegrationLists.ts. Do not modify by hand

module.exports = [
  {
    name: 'airtable',
    dirName: 'integration-airtable',
    varName: 'integrationAirtable',
    imports: {
      def: '@usevenice/connector-airtable/def',
      server: '@usevenice/connector-airtable/server',
    },
  },
  {
    dirName: 'integration-alphavantage',
    varName: 'integrationAlphavantage',
    imports: {},
  },
  {
    name: 'beancount',
    dirName: 'integration-beancount',
    varName: 'integrationBeancount',
    imports: {
      def: '@usevenice/connector-beancount/def',
      server: '@usevenice/connector-beancount/server',
    },
  },
  {
    name: 'brex',
    dirName: 'integration-brex',
    varName: 'integrationBrex',
    imports: {
      def: '@usevenice/connector-brex/def',
      server: '@usevenice/connector-brex/server',
    },
  },
  {dirName: 'integration-copilot', varName: 'integrationCopilot', imports: {}},
  {
    name: 'debug',
    dirName: 'integration-debug',
    varName: 'integrationDebug',
    imports: {
      def: '@usevenice/connector-debug/def',
      server: '@usevenice/connector-debug/server',
    },
  },
  {
    name: 'discord',
    dirName: 'integration-discord',
    varName: 'integrationDiscord',
    imports: {
      def: '@usevenice/connector-discord/def',
      server: '@usevenice/connector-discord/server',
    },
  },
  {
    dirName: 'integration-expensify',
    varName: 'integrationExpensify',
    imports: {},
  },
  {
    name: 'firebase',
    dirName: 'integration-firebase',
    varName: 'integrationFirebase',
    imports: {
      def: '@usevenice/connector-firebase/def',
      server: '@usevenice/connector-firebase/server',
    },
  },
  {
    name: 'foreceipt',
    dirName: 'integration-foreceipt',
    varName: 'integrationForeceipt',
    imports: {
      def: '@usevenice/connector-foreceipt/def',
      server: '@usevenice/connector-foreceipt/server',
    },
  },
  {
    name: 'fs',
    dirName: 'integration-fs',
    varName: 'integrationFs',
    imports: {
      def: '@usevenice/connector-fs/def',
      server: '@usevenice/connector-fs/server',
    },
  },
  {
    name: 'heron',
    dirName: 'integration-heron',
    varName: 'integrationHeron',
    imports: {
      def: '@usevenice/connector-heron/def',
      server: '@usevenice/connector-heron/server',
    },
  },
  {
    name: 'lunchmoney',
    dirName: 'integration-lunchmoney',
    varName: 'integrationLunchmoney',
    imports: {
      def: '@usevenice/connector-lunchmoney/def',
      server: '@usevenice/connector-lunchmoney/server',
    },
  },
  {
    name: 'mercury',
    dirName: 'integration-mercury',
    varName: 'integrationMercury',
    imports: {def: '@usevenice/connector-mercury/def'},
  },
  {
    name: 'merge',
    dirName: 'integration-merge',
    varName: 'integrationMerge',
    imports: {
      def: '@usevenice/connector-merge/def',
      client: '@usevenice/connector-merge/client',
      server: '@usevenice/connector-merge/server',
    },
  },
  {
    name: 'mongodb',
    dirName: 'integration-mongodb',
    varName: 'integrationMongodb',
    imports: {
      def: '@usevenice/connector-mongodb/def',
      server: '@usevenice/connector-mongodb/server',
    },
  },
  {
    name: 'moota',
    dirName: 'integration-moota',
    varName: 'integrationMoota',
    imports: {
      def: '@usevenice/connector-moota/def',
      server: '@usevenice/connector-moota/server',
    },
  },
  {dirName: 'integration-notion', varName: 'integrationNotion', imports: {}},
  {
    name: 'onebrick',
    dirName: 'integration-onebrick',
    varName: 'integrationOnebrick',
    imports: {
      def: '@usevenice/connector-onebrick/def',
      client: '@usevenice/connector-onebrick/client',
      server: '@usevenice/connector-onebrick/server',
    },
  },
  {
    name: 'plaid',
    dirName: 'integration-plaid',
    varName: 'integrationPlaid',
    imports: {
      def: '@usevenice/connector-plaid/def',
      client: '@usevenice/connector-plaid/client',
      server: '@usevenice/connector-plaid/server',
    },
  },
  {
    name: 'postgres',
    dirName: 'integration-postgres',
    varName: 'integrationPostgres',
    imports: {
      def: '@usevenice/connector-postgres/def',
      server: '@usevenice/connector-postgres/server',
    },
  },
  {
    name: 'qbo',
    dirName: 'integration-qbo',
    varName: 'integrationQbo',
    imports: {
      def: '@usevenice/connector-qbo/def',
      server: '@usevenice/connector-qbo/server',
    },
  },
  {
    name: 'ramp',
    dirName: 'integration-ramp',
    varName: 'integrationRamp',
    imports: {
      def: '@usevenice/connector-ramp/def',
      server: '@usevenice/connector-ramp/server',
    },
  },
  {
    name: 'saltedge',
    dirName: 'integration-saltedge',
    varName: 'integrationSaltedge',
    imports: {
      def: '@usevenice/connector-saltedge/def',
      server: '@usevenice/connector-saltedge/server',
    },
  },
  {
    name: 'splitwise',
    dirName: 'integration-splitwise',
    varName: 'integrationSplitwise',
    imports: {
      def: '@usevenice/connector-splitwise/def',
      server: '@usevenice/connector-splitwise/server',
    },
  },
  {
    name: 'spreadsheet',
    dirName: 'integration-spreadsheet',
    varName: 'integrationSpreadsheet',
    imports: {
      def: '@usevenice/connector-spreadsheet/def',
      server: '@usevenice/connector-spreadsheet/server',
    },
  },
  {
    name: 'stripe',
    dirName: 'integration-stripe',
    varName: 'integrationStripe',
    imports: {
      def: '@usevenice/connector-stripe/def',
      server: '@usevenice/connector-stripe/server',
    },
  },
  {
    name: 'teller',
    dirName: 'integration-teller',
    varName: 'integrationTeller',
    imports: {
      def: '@usevenice/connector-teller/def',
      client: '@usevenice/connector-teller/client',
      server: '@usevenice/connector-teller/server',
    },
  },
  {
    name: 'toggl',
    dirName: 'integration-toggl',
    varName: 'integrationToggl',
    imports: {
      def: '@usevenice/connector-toggl/def',
      server: '@usevenice/connector-toggl/server',
    },
  },
  {
    name: 'venmo',
    dirName: 'integration-venmo',
    varName: 'integrationVenmo',
    imports: {def: '@usevenice/connector-venmo/def'},
  },
  {
    name: 'webhook',
    dirName: 'integration-webhook',
    varName: 'integrationWebhook',
    imports: {
      def: '@usevenice/connector-webhook/def',
      server: '@usevenice/connector-webhook/server',
    },
  },
  {
    name: 'wise',
    dirName: 'integration-wise',
    varName: 'integrationWise',
    imports: {
      def: '@usevenice/connector-wise/def',
      server: '@usevenice/connector-wise/server',
    },
  },
  {
    name: 'yodlee',
    dirName: 'integration-yodlee',
    varName: 'integrationYodlee',
    imports: {
      def: '@usevenice/connector-yodlee/def',
      client: '@usevenice/connector-yodlee/client',
      server: '@usevenice/connector-yodlee/server',
    },
  },
]
