// generated by _generateIntegrationLists.ts. Do not modify by hand

module.exports = [
  {
    dirName: 'core-integration-airtable',
    varName: 'coreIntegrationAirtable',
    imports: {},
  },
  {
    dirName: 'core-integration-firebase',
    varName: 'coreIntegrationFirebase',
    imports: {},
  },
  {dirName: 'core-integration-fs', varName: 'coreIntegrationFs', imports: {}},
  {
    dirName: 'core-integration-mongodb',
    varName: 'coreIntegrationMongodb',
    imports: {},
  },
  {
    dirName: 'core-integration-postgres',
    varName: 'coreIntegrationPostgres',
    imports: {},
  },
  {
    dirName: 'core-integration-redis',
    varName: 'coreIntegrationRedis',
    imports: {},
  },
  {
    dirName: 'core-integration-webhook',
    varName: 'coreIntegrationWebhook',
    imports: {},
  },
  {
    dirName: 'integration-alphavantage',
    varName: 'integrationAlphavantage',
    imports: {},
  },
  {
    dirName: 'integration-beancount',
    varName: 'integrationBeancount',
    imports: {},
  },
  {
    name: 'brex',
    dirName: 'integration-brex',
    varName: 'integrationBrex',
    imports: {
      def: '@usevenice/integration-brex/def',
      server: '@usevenice/integration-brex/server',
    },
  },
  {
    dirName: 'integration-expensify',
    varName: 'integrationExpensify',
    imports: {},
  },
  {
    dirName: 'integration-foreceipt',
    varName: 'integrationForeceipt',
    imports: {},
  },
  {
    name: 'heron',
    dirName: 'integration-heron',
    varName: 'integrationHeron',
    imports: {
      def: '@usevenice/integration-heron/def',
      server: '@usevenice/integration-heron/server',
    },
  },
  {
    dirName: 'integration-lunchmoney',
    varName: 'integrationLunchmoney',
    imports: {},
  },
  {
    name: 'mercury',
    dirName: 'integration-mercury',
    varName: 'integrationMercury',
    imports: {def: '@usevenice/integration-mercury/def'},
  },
  {
    name: 'merge',
    dirName: 'integration-merge',
    varName: 'integrationMerge',
    imports: {
      def: '@usevenice/integration-merge/def',
      client: '@usevenice/integration-merge/client',
      server: '@usevenice/integration-merge/server',
    },
  },
  {dirName: 'integration-moota', varName: 'integrationMoota', imports: {}},
  {
    name: 'onebrick',
    dirName: 'integration-onebrick',
    varName: 'integrationOnebrick',
    imports: {
      def: '@usevenice/integration-onebrick/def',
      client: '@usevenice/integration-onebrick/client',
      server: '@usevenice/integration-onebrick/server',
    },
  },
  {
    name: 'plaid',
    dirName: 'integration-plaid',
    varName: 'integrationPlaid',
    imports: {
      def: '@usevenice/integration-plaid/def',
      client: '@usevenice/integration-plaid/client',
      server: '@usevenice/integration-plaid/server',
    },
  },
  {
    dirName: 'integration-postgres',
    varName: 'integrationPostgres',
    imports: {},
  },
  {dirName: 'integration-qbo', varName: 'integrationQbo', imports: {}},
  {dirName: 'integration-ramp', varName: 'integrationRamp', imports: {}},
  {
    dirName: 'integration-saltedge',
    varName: 'integrationSaltedge',
    imports: {},
  },
  {
    dirName: 'integration-splitwise',
    varName: 'integrationSplitwise',
    imports: {},
  },
  {
    dirName: 'integration-spreadsheet',
    varName: 'integrationSpreadsheet',
    imports: {},
  },
  {
    name: 'stripe',
    dirName: 'integration-stripe',
    varName: 'integrationStripe',
    imports: {
      def: '@usevenice/integration-stripe/def',
      server: '@usevenice/integration-stripe/server',
    },
  },
  {
    name: 'teller',
    dirName: 'integration-teller',
    varName: 'integrationTeller',
    imports: {
      def: '@usevenice/integration-teller/def',
      client: '@usevenice/integration-teller/client',
      server: '@usevenice/integration-teller/server',
    },
  },
  {dirName: 'integration-toggl', varName: 'integrationToggl', imports: {}},
  {dirName: 'integration-venmo', varName: 'integrationVenmo', imports: {}},
  {dirName: 'integration-wise', varName: 'integrationWise', imports: {}},
  {
    name: 'yodlee',
    dirName: 'integration-yodlee',
    varName: 'integrationYodlee',
    imports: {
      def: '@usevenice/integration-yodlee/def',
      client: '@usevenice/integration-yodlee/client',
      server: '@usevenice/integration-yodlee/server',
    },
  },
]
