// generated by _generateIntegrationLists.ts. Do not modify by hand

module.exports = [
  {
    dirName: 'core-integration-firebase',
    varName: 'coreIntegrationFirebase',
    imports: {},
  },
  {dirName: 'core-integration-fs', varName: 'coreIntegrationFs', imports: {}},
  {
    dirName: 'core-integration-mongodb',
    varName: 'coreIntegrationMongodb',
    imports: {},
  },
  {
    dirName: 'core-integration-postgres',
    varName: 'coreIntegrationPostgres',
    imports: {},
  },
  {
    dirName: 'core-integration-redis',
    varName: 'coreIntegrationRedis',
    imports: {},
  },
  {
    dirName: 'core-integration-webhook',
    varName: 'coreIntegrationWebhook',
    imports: {},
  },
  {
    name: 'airtable',
    dirName: 'integration-airtable',
    varName: 'integrationAirtable',
    imports: {
      def: '@usevenice/integration-airtable/def',
      server: '@usevenice/integration-airtable/server',
    },
  },
  {
    dirName: 'integration-alphavantage',
    varName: 'integrationAlphavantage',
    imports: {},
  },
  {
    name: 'beancount',
    dirName: 'integration-beancount',
    varName: 'integrationBeancount',
    imports: {
      def: '@usevenice/integration-beancount/def',
      server: '@usevenice/integration-beancount/server',
    },
  },
  {
    name: 'brex',
    dirName: 'integration-brex',
    varName: 'integrationBrex',
    imports: {
      def: '@usevenice/integration-brex/def',
      server: '@usevenice/integration-brex/server',
    },
  },
  {
    dirName: 'integration-expensify',
    varName: 'integrationExpensify',
    imports: {},
  },
  {
    name: 'foreceipt',
    dirName: 'integration-foreceipt',
    varName: 'integrationForeceipt',
    imports: {
      def: '@usevenice/integration-foreceipt/def',
      server: '@usevenice/integration-foreceipt/server',
    },
  },
  {
    name: 'heron',
    dirName: 'integration-heron',
    varName: 'integrationHeron',
    imports: {
      def: '@usevenice/integration-heron/def',
      server: '@usevenice/integration-heron/server',
    },
  },
  {
    name: 'lunchmoney',
    dirName: 'integration-lunchmoney',
    varName: 'integrationLunchmoney',
    imports: {
      def: '@usevenice/integration-lunchmoney/def',
      server: '@usevenice/integration-lunchmoney/server',
    },
  },
  {
    name: 'mercury',
    dirName: 'integration-mercury',
    varName: 'integrationMercury',
    imports: {def: '@usevenice/integration-mercury/def'},
  },
  {
    name: 'merge',
    dirName: 'integration-merge',
    varName: 'integrationMerge',
    imports: {
      def: '@usevenice/integration-merge/def',
      client: '@usevenice/integration-merge/client',
      server: '@usevenice/integration-merge/server',
    },
  },
  {
    name: 'moota',
    dirName: 'integration-moota',
    varName: 'integrationMoota',
    imports: {
      def: '@usevenice/integration-moota/def',
      server: '@usevenice/integration-moota/server',
    },
  },
  {
    name: 'onebrick',
    dirName: 'integration-onebrick',
    varName: 'integrationOnebrick',
    imports: {
      def: '@usevenice/integration-onebrick/def',
      client: '@usevenice/integration-onebrick/client',
      server: '@usevenice/integration-onebrick/server',
    },
  },
  {
    name: 'plaid',
    dirName: 'integration-plaid',
    varName: 'integrationPlaid',
    imports: {
      def: '@usevenice/integration-plaid/def',
      client: '@usevenice/integration-plaid/client',
      server: '@usevenice/integration-plaid/server',
    },
  },
  {
    name: 'postgres',
    dirName: 'integration-postgres',
    varName: 'integrationPostgres',
    imports: {
      def: '@usevenice/integration-postgres/def',
      server: '@usevenice/integration-postgres/server',
    },
  },
  {
    name: 'qbo',
    dirName: 'integration-qbo',
    varName: 'integrationQbo',
    imports: {
      def: '@usevenice/integration-qbo/def',
      server: '@usevenice/integration-qbo/server',
    },
  },
  {
    name: 'ramp',
    dirName: 'integration-ramp',
    varName: 'integrationRamp',
    imports: {
      def: '@usevenice/integration-ramp/def',
      server: '@usevenice/integration-ramp/server',
    },
  },
  {
    name: 'saltedge',
    dirName: 'integration-saltedge',
    varName: 'integrationSaltedge',
    imports: {
      def: '@usevenice/integration-saltedge/def',
      server: '@usevenice/integration-saltedge/server',
    },
  },
  {
    name: 'splitwise',
    dirName: 'integration-splitwise',
    varName: 'integrationSplitwise',
    imports: {
      def: '@usevenice/integration-splitwise/def',
      server: '@usevenice/integration-splitwise/server',
    },
  },
  {
    name: 'spreadsheet',
    dirName: 'integration-spreadsheet',
    varName: 'integrationSpreadsheet',
    imports: {
      def: '@usevenice/integration-spreadsheet/def',
      server: '@usevenice/integration-spreadsheet/server',
    },
  },
  {
    name: 'stripe',
    dirName: 'integration-stripe',
    varName: 'integrationStripe',
    imports: {
      def: '@usevenice/integration-stripe/def',
      server: '@usevenice/integration-stripe/server',
    },
  },
  {
    name: 'teller',
    dirName: 'integration-teller',
    varName: 'integrationTeller',
    imports: {
      def: '@usevenice/integration-teller/def',
      client: '@usevenice/integration-teller/client',
      server: '@usevenice/integration-teller/server',
    },
  },
  {
    name: 'toggl',
    dirName: 'integration-toggl',
    varName: 'integrationToggl',
    imports: {
      def: '@usevenice/integration-toggl/def',
      server: '@usevenice/integration-toggl/server',
    },
  },
  {
    name: 'venmo',
    dirName: 'integration-venmo',
    varName: 'integrationVenmo',
    imports: {def: '@usevenice/integration-venmo/def'},
  },
  {
    name: 'wise',
    dirName: 'integration-wise',
    varName: 'integrationWise',
    imports: {
      def: '@usevenice/integration-wise/def',
      server: '@usevenice/integration-wise/server',
    },
  },
  {
    name: 'yodlee',
    dirName: 'integration-yodlee',
    varName: 'integrationYodlee',
    imports: {
      def: '@usevenice/integration-yodlee/def',
      client: '@usevenice/integration-yodlee/client',
      server: '@usevenice/integration-yodlee/server',
    },
  },
]
