// generated by _generateConnectorLists.ts. Do not modify by hand
import {default as connectorAirtable} from '@usevenice/connector-airtable/server'
import {default as connectorApollo} from '@usevenice/connector-apollo/server'
import {default as connectorBeancount} from '@usevenice/connector-beancount/server'
import {default as connectorBrex} from '@usevenice/connector-brex/server'
import {default as connectorDebug} from '@usevenice/connector-debug/server'
import {default as connectorDiscord} from '@usevenice/connector-discord/server'
import {default as connectorFirebase} from '@usevenice/connector-firebase/server'
import {default as connectorForeceipt} from '@usevenice/connector-foreceipt/server'
import {default as connectorFs} from '@usevenice/connector-fs/server'
import {default as connectorHeron} from '@usevenice/connector-heron/server'
import {default as connectorLunchmoney} from '@usevenice/connector-lunchmoney/server'
import {default as connectorMerge} from '@usevenice/connector-merge/server'
import {default as connectorMongodb} from '@usevenice/connector-mongodb/server'
import {default as connectorMoota} from '@usevenice/connector-moota/server'
import {default as connectorOnebrick} from '@usevenice/connector-onebrick/server'
import {default as connectorOutreach} from '@usevenice/connector-outreach/server'
import {default as connectorPlaid} from '@usevenice/connector-plaid/server'
import {default as connectorPostgres} from '@usevenice/connector-postgres/server'
import {default as connectorQbo} from '@usevenice/connector-qbo/server'
import {default as connectorRamp} from '@usevenice/connector-ramp/server'
import {default as connectorSalesloft} from '@usevenice/connector-salesloft/server'
import {default as connectorSaltedge} from '@usevenice/connector-saltedge/server'
import {default as connectorSplitwise} from '@usevenice/connector-splitwise/server'
import {default as connectorSpreadsheet} from '@usevenice/connector-spreadsheet/server'
import {default as connectorStripe} from '@usevenice/connector-stripe/server'
import {default as connectorTeller} from '@usevenice/connector-teller/server'
import {default as connectorToggl} from '@usevenice/connector-toggl/server'
import {default as connectorTwenty} from '@usevenice/connector-twenty/server'
import {default as connectorWebhook} from '@usevenice/connector-webhook/server'
import {default as connectorWise} from '@usevenice/connector-wise/server'
import {default as connectorYodlee} from '@usevenice/connector-yodlee/server'

export const serverConnectors = {
  airtable: connectorAirtable,
  apollo: connectorApollo,
  beancount: connectorBeancount,
  brex: connectorBrex,
  debug: connectorDebug,
  discord: connectorDiscord,
  firebase: connectorFirebase,
  foreceipt: connectorForeceipt,
  fs: connectorFs,
  heron: connectorHeron,
  lunchmoney: connectorLunchmoney,
  merge: connectorMerge,
  mongodb: connectorMongodb,
  moota: connectorMoota,
  onebrick: connectorOnebrick,
  outreach: connectorOutreach,
  plaid: connectorPlaid,
  postgres: connectorPostgres,
  qbo: connectorQbo,
  ramp: connectorRamp,
  salesloft: connectorSalesloft,
  saltedge: connectorSaltedge,
  splitwise: connectorSplitwise,
  spreadsheet: connectorSpreadsheet,
  stripe: connectorStripe,
  teller: connectorTeller,
  toggl: connectorToggl,
  twenty: connectorTwenty,
  webhook: connectorWebhook,
  wise: connectorWise,
  yodlee: connectorYodlee,
}
