// generated by _generateConnectorLists.ts. Do not modify by hand
import {default as connectorAirtable_def} from '@usevenice/connector-airtable/def'
import {default as connectorAirtable_server} from '@usevenice/connector-airtable/server'
import {default as connectorApollo_def} from '@usevenice/connector-apollo/def'
import {default as connectorApollo_server} from '@usevenice/connector-apollo/server'
import {default as connectorBeancount_def} from '@usevenice/connector-beancount/def'
import {default as connectorBeancount_server} from '@usevenice/connector-beancount/server'
import {default as connectorBrex_def} from '@usevenice/connector-brex/def'
import {default as connectorBrex_server} from '@usevenice/connector-brex/server'
import {default as connectorDebug_def} from '@usevenice/connector-debug/def'
import {default as connectorDebug_server} from '@usevenice/connector-debug/server'
import {default as connectorDiscord_def} from '@usevenice/connector-discord/def'
import {default as connectorDiscord_server} from '@usevenice/connector-discord/server'
import {default as connectorFirebase_def} from '@usevenice/connector-firebase/def'
import {default as connectorFirebase_server} from '@usevenice/connector-firebase/server'
import {default as connectorForeceipt_def} from '@usevenice/connector-foreceipt/def'
import {default as connectorForeceipt_server} from '@usevenice/connector-foreceipt/server'
import {default as connectorFs_def} from '@usevenice/connector-fs/def'
import {default as connectorFs_server} from '@usevenice/connector-fs/server'
import {default as connectorHeron_def} from '@usevenice/connector-heron/def'
import {default as connectorHeron_server} from '@usevenice/connector-heron/server'
import {default as connectorLunchmoney_def} from '@usevenice/connector-lunchmoney/def'
import {default as connectorLunchmoney_server} from '@usevenice/connector-lunchmoney/server'
import {default as connectorMercury_def} from '@usevenice/connector-mercury/def'
import {default as connectorMerge_def} from '@usevenice/connector-merge/def'
import {default as connectorMerge_server} from '@usevenice/connector-merge/server'
import {default as connectorMongodb_def} from '@usevenice/connector-mongodb/def'
import {default as connectorMongodb_server} from '@usevenice/connector-mongodb/server'
import {default as connectorMoota_def} from '@usevenice/connector-moota/def'
import {default as connectorMoota_server} from '@usevenice/connector-moota/server'
import {default as connectorOnebrick_def} from '@usevenice/connector-onebrick/def'
import {default as connectorOnebrick_server} from '@usevenice/connector-onebrick/server'
import {default as connectorOutreach_def} from '@usevenice/connector-outreach/def'
import {default as connectorOutreach_server} from '@usevenice/connector-outreach/server'
import {default as connectorPlaid_def} from '@usevenice/connector-plaid/def'
import {default as connectorPlaid_server} from '@usevenice/connector-plaid/server'
import {default as connectorPostgres_def} from '@usevenice/connector-postgres/def'
import {default as connectorPostgres_server} from '@usevenice/connector-postgres/server'
import {default as connectorQbo_def} from '@usevenice/connector-qbo/def'
import {default as connectorQbo_server} from '@usevenice/connector-qbo/server'
import {default as connectorRamp_def} from '@usevenice/connector-ramp/def'
import {default as connectorRamp_server} from '@usevenice/connector-ramp/server'
import {default as connectorSaltedge_def} from '@usevenice/connector-saltedge/def'
import {default as connectorSaltedge_server} from '@usevenice/connector-saltedge/server'
import {default as connectorSplitwise_def} from '@usevenice/connector-splitwise/def'
import {default as connectorSplitwise_server} from '@usevenice/connector-splitwise/server'
import {default as connectorSpreadsheet_def} from '@usevenice/connector-spreadsheet/def'
import {default as connectorSpreadsheet_server} from '@usevenice/connector-spreadsheet/server'
import {default as connectorStripe_def} from '@usevenice/connector-stripe/def'
import {default as connectorStripe_server} from '@usevenice/connector-stripe/server'
import {default as connectorTeller_def} from '@usevenice/connector-teller/def'
import {default as connectorTeller_server} from '@usevenice/connector-teller/server'
import {default as connectorToggl_def} from '@usevenice/connector-toggl/def'
import {default as connectorToggl_server} from '@usevenice/connector-toggl/server'
import {default as connectorVenmo_def} from '@usevenice/connector-venmo/def'
import {default as connectorWebhook_def} from '@usevenice/connector-webhook/def'
import {default as connectorWebhook_server} from '@usevenice/connector-webhook/server'
import {default as connectorWise_def} from '@usevenice/connector-wise/def'
import {default as connectorWise_server} from '@usevenice/connector-wise/server'
import {default as connectorYodlee_def} from '@usevenice/connector-yodlee/def'
import {default as connectorYodlee_server} from '@usevenice/connector-yodlee/server'

const connectorAirtable = {
  ...connectorAirtable_def,
  ...connectorAirtable_server,
}

const connectorApollo = {
  ...connectorApollo_def,
  ...connectorApollo_server,
}

const connectorBeancount = {
  ...connectorBeancount_def,
  ...connectorBeancount_server,
}

const connectorBrex = {
  ...connectorBrex_def,
  ...connectorBrex_server,
}

const connectorDebug = {
  ...connectorDebug_def,
  ...connectorDebug_server,
}

const connectorDiscord = {
  ...connectorDiscord_def,
  ...connectorDiscord_server,
}

const connectorFirebase = {
  ...connectorFirebase_def,
  ...connectorFirebase_server,
}

const connectorForeceipt = {
  ...connectorForeceipt_def,
  ...connectorForeceipt_server,
}

const connectorFs = {
  ...connectorFs_def,
  ...connectorFs_server,
}

const connectorHeron = {
  ...connectorHeron_def,
  ...connectorHeron_server,
}

const connectorLunchmoney = {
  ...connectorLunchmoney_def,
  ...connectorLunchmoney_server,
}

const connectorMercury = {
  ...connectorMercury_def,
}

const connectorMerge = {
  ...connectorMerge_def,
  ...connectorMerge_server,
}

const connectorMongodb = {
  ...connectorMongodb_def,
  ...connectorMongodb_server,
}

const connectorMoota = {
  ...connectorMoota_def,
  ...connectorMoota_server,
}

const connectorOnebrick = {
  ...connectorOnebrick_def,
  ...connectorOnebrick_server,
}

const connectorOutreach = {
  ...connectorOutreach_def,
  ...connectorOutreach_server,
}

const connectorPlaid = {
  ...connectorPlaid_def,
  ...connectorPlaid_server,
}

const connectorPostgres = {
  ...connectorPostgres_def,
  ...connectorPostgres_server,
}

const connectorQbo = {
  ...connectorQbo_def,
  ...connectorQbo_server,
}

const connectorRamp = {
  ...connectorRamp_def,
  ...connectorRamp_server,
}

const connectorSaltedge = {
  ...connectorSaltedge_def,
  ...connectorSaltedge_server,
}

const connectorSplitwise = {
  ...connectorSplitwise_def,
  ...connectorSplitwise_server,
}

const connectorSpreadsheet = {
  ...connectorSpreadsheet_def,
  ...connectorSpreadsheet_server,
}

const connectorStripe = {
  ...connectorStripe_def,
  ...connectorStripe_server,
}

const connectorTeller = {
  ...connectorTeller_def,
  ...connectorTeller_server,
}

const connectorToggl = {
  ...connectorToggl_def,
  ...connectorToggl_server,
}

const connectorVenmo = {
  ...connectorVenmo_def,
}

const connectorWebhook = {
  ...connectorWebhook_def,
  ...connectorWebhook_server,
}

const connectorWise = {
  ...connectorWise_def,
  ...connectorWise_server,
}

const connectorYodlee = {
  ...connectorYodlee_def,
  ...connectorYodlee_server,
}

export const mergedConnectors = {
  airtable: connectorAirtable,
  apollo: connectorApollo,
  beancount: connectorBeancount,
  brex: connectorBrex,
  debug: connectorDebug,
  discord: connectorDiscord,
  firebase: connectorFirebase,
  foreceipt: connectorForeceipt,
  fs: connectorFs,
  heron: connectorHeron,
  lunchmoney: connectorLunchmoney,
  mercury: connectorMercury,
  merge: connectorMerge,
  mongodb: connectorMongodb,
  moota: connectorMoota,
  onebrick: connectorOnebrick,
  outreach: connectorOutreach,
  plaid: connectorPlaid,
  postgres: connectorPostgres,
  qbo: connectorQbo,
  ramp: connectorRamp,
  saltedge: connectorSaltedge,
  splitwise: connectorSplitwise,
  spreadsheet: connectorSpreadsheet,
  stripe: connectorStripe,
  teller: connectorTeller,
  toggl: connectorToggl,
  venmo: connectorVenmo,
  webhook: connectorWebhook,
  wise: connectorWise,
  yodlee: connectorYodlee,
}
