// generated by _generateConnectorLists.ts. Do not modify by hand
import {default as connectorAirtable} from '@usevenice/connector-airtable/def'
import {default as connectorApollo} from '@usevenice/connector-apollo/def'
import {default as connectorBeancount} from '@usevenice/connector-beancount/def'
import {default as connectorBrex} from '@usevenice/connector-brex/def'
import {default as connectorDebug} from '@usevenice/connector-debug/def'
import {default as connectorDiscord} from '@usevenice/connector-discord/def'
import {default as connectorFirebase} from '@usevenice/connector-firebase/def'
import {default as connectorForeceipt} from '@usevenice/connector-foreceipt/def'
import {default as connectorFs} from '@usevenice/connector-fs/def'
import {default as connectorHeron} from '@usevenice/connector-heron/def'
import {default as connectorLunchmoney} from '@usevenice/connector-lunchmoney/def'
import {default as connectorMercury} from '@usevenice/connector-mercury/def'
import {default as connectorMerge} from '@usevenice/connector-merge/def'
import {default as connectorMongodb} from '@usevenice/connector-mongodb/def'
import {default as connectorMoota} from '@usevenice/connector-moota/def'
import {default as connectorOnebrick} from '@usevenice/connector-onebrick/def'
import {default as connectorOutreach} from '@usevenice/connector-outreach/def'
import {default as connectorPlaid} from '@usevenice/connector-plaid/def'
import {default as connectorPostgres} from '@usevenice/connector-postgres/def'
import {default as connectorQbo} from '@usevenice/connector-qbo/def'
import {default as connectorRamp} from '@usevenice/connector-ramp/def'
import {default as connectorSalesloft} from '@usevenice/connector-salesloft/def'
import {default as connectorSaltedge} from '@usevenice/connector-saltedge/def'
import {default as connectorSplitwise} from '@usevenice/connector-splitwise/def'
import {default as connectorSpreadsheet} from '@usevenice/connector-spreadsheet/def'
import {default as connectorStripe} from '@usevenice/connector-stripe/def'
import {default as connectorTeller} from '@usevenice/connector-teller/def'
import {default as connectorToggl} from '@usevenice/connector-toggl/def'
import {default as connectorVenmo} from '@usevenice/connector-venmo/def'
import {default as connectorWebhook} from '@usevenice/connector-webhook/def'
import {default as connectorWise} from '@usevenice/connector-wise/def'
import {default as connectorYodlee} from '@usevenice/connector-yodlee/def'

export const defConnectors = {
  airtable: connectorAirtable,
  apollo: connectorApollo,
  beancount: connectorBeancount,
  brex: connectorBrex,
  debug: connectorDebug,
  discord: connectorDiscord,
  firebase: connectorFirebase,
  foreceipt: connectorForeceipt,
  fs: connectorFs,
  heron: connectorHeron,
  lunchmoney: connectorLunchmoney,
  mercury: connectorMercury,
  merge: connectorMerge,
  mongodb: connectorMongodb,
  moota: connectorMoota,
  onebrick: connectorOnebrick,
  outreach: connectorOutreach,
  plaid: connectorPlaid,
  postgres: connectorPostgres,
  qbo: connectorQbo,
  ramp: connectorRamp,
  salesloft: connectorSalesloft,
  saltedge: connectorSaltedge,
  splitwise: connectorSplitwise,
  spreadsheet: connectorSpreadsheet,
  stripe: connectorStripe,
  teller: connectorTeller,
  toggl: connectorToggl,
  venmo: connectorVenmo,
  webhook: connectorWebhook,
  wise: connectorWise,
  yodlee: connectorYodlee,
}
