// generated by _generateConnectorLists.ts. Do not modify by hand
import {default as connectorMerge} from '@usevenice/connector-merge/client'
import {default as connectorOnebrick} from '@usevenice/connector-onebrick/client'
import {default as connectorPlaid} from '@usevenice/connector-plaid/client'
import {default as connectorTeller} from '@usevenice/connector-teller/client'
import {default as connectorYodlee} from '@usevenice/connector-yodlee/client'

export const clientConnectors = {
  merge: connectorMerge,
  onebrick: connectorOnebrick,
  plaid: connectorPlaid,
  teller: connectorTeller,
  yodlee: connectorYodlee,
}
